// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kvs/kvs.proto

/*
Package db is a generated protocol buffer package.

It is generated from these files:
	kvs/kvs.proto

It has these top-level messages:
	KeyValuePair
	ListRequest
	GetRequest
	GetResponse
	SetResponse
	RemoveRequest
	RemoveResponse
*/
package db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KeyValuePair struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *KeyValuePair) Reset()                    { *m = KeyValuePair{} }
func (m *KeyValuePair) String() string            { return proto.CompactTextString(m) }
func (*KeyValuePair) ProtoMessage()               {}
func (*KeyValuePair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *KeyValuePair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValuePair) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ListRequest struct {
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResponse struct {
	// Types that are valid to be assigned to GetResponseOneOf:
	//	*GetResponse_Value
	//	*GetResponse_Error
	GetResponseOneOf isGetResponse_GetResponseOneOf `protobuf_oneof:"get_response_one_of"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isGetResponse_GetResponseOneOf interface {
	isGetResponse_GetResponseOneOf()
}

type GetResponse_Value struct {
	Value string `protobuf:"bytes,1,opt,name=value,oneof"`
}
type GetResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,oneof"`
}

func (*GetResponse_Value) isGetResponse_GetResponseOneOf() {}
func (*GetResponse_Error) isGetResponse_GetResponseOneOf() {}

func (m *GetResponse) GetGetResponseOneOf() isGetResponse_GetResponseOneOf {
	if m != nil {
		return m.GetResponseOneOf
	}
	return nil
}

func (m *GetResponse) GetValue() string {
	if x, ok := m.GetGetResponseOneOf().(*GetResponse_Value); ok {
		return x.Value
	}
	return ""
}

func (m *GetResponse) GetError() string {
	if x, ok := m.GetGetResponseOneOf().(*GetResponse_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GetResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GetResponse_OneofMarshaler, _GetResponse_OneofUnmarshaler, _GetResponse_OneofSizer, []interface{}{
		(*GetResponse_Value)(nil),
		(*GetResponse_Error)(nil),
	}
}

func _GetResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GetResponse)
	// get_response_one_of
	switch x := m.GetResponseOneOf.(type) {
	case *GetResponse_Value:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Value)
	case *GetResponse_Error:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Error)
	case nil:
	default:
		return fmt.Errorf("GetResponse.GetResponseOneOf has unexpected type %T", x)
	}
	return nil
}

func _GetResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GetResponse)
	switch tag {
	case 1: // get_response_one_of.value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.GetResponseOneOf = &GetResponse_Value{x}
		return true, err
	case 2: // get_response_one_of.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.GetResponseOneOf = &GetResponse_Error{x}
		return true, err
	default:
		return false, nil
	}
}

func _GetResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GetResponse)
	// get_response_one_of
	switch x := m.GetResponseOneOf.(type) {
	case *GetResponse_Value:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Value)))
		n += len(x.Value)
	case *GetResponse_Error:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Error)))
		n += len(x.Error)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SetResponse struct {
	// Types that are valid to be assigned to SetResponseOneOf:
	//	*SetResponse_Value
	//	*SetResponse_Error
	SetResponseOneOf isSetResponse_SetResponseOneOf `protobuf_oneof:"set_response_one_of"`
}

func (m *SetResponse) Reset()                    { *m = SetResponse{} }
func (m *SetResponse) String() string            { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()               {}
func (*SetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type isSetResponse_SetResponseOneOf interface {
	isSetResponse_SetResponseOneOf()
}

type SetResponse_Value struct {
	Value string `protobuf:"bytes,1,opt,name=value,oneof"`
}
type SetResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,oneof"`
}

func (*SetResponse_Value) isSetResponse_SetResponseOneOf() {}
func (*SetResponse_Error) isSetResponse_SetResponseOneOf() {}

func (m *SetResponse) GetSetResponseOneOf() isSetResponse_SetResponseOneOf {
	if m != nil {
		return m.SetResponseOneOf
	}
	return nil
}

func (m *SetResponse) GetValue() string {
	if x, ok := m.GetSetResponseOneOf().(*SetResponse_Value); ok {
		return x.Value
	}
	return ""
}

func (m *SetResponse) GetError() string {
	if x, ok := m.GetSetResponseOneOf().(*SetResponse_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SetResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SetResponse_OneofMarshaler, _SetResponse_OneofUnmarshaler, _SetResponse_OneofSizer, []interface{}{
		(*SetResponse_Value)(nil),
		(*SetResponse_Error)(nil),
	}
}

func _SetResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SetResponse)
	// set_response_one_of
	switch x := m.SetResponseOneOf.(type) {
	case *SetResponse_Value:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Value)
	case *SetResponse_Error:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Error)
	case nil:
	default:
		return fmt.Errorf("SetResponse.SetResponseOneOf has unexpected type %T", x)
	}
	return nil
}

func _SetResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SetResponse)
	switch tag {
	case 1: // set_response_one_of.value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.SetResponseOneOf = &SetResponse_Value{x}
		return true, err
	case 2: // set_response_one_of.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.SetResponseOneOf = &SetResponse_Error{x}
		return true, err
	default:
		return false, nil
	}
}

func _SetResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SetResponse)
	// set_response_one_of
	switch x := m.SetResponseOneOf.(type) {
	case *SetResponse_Value:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Value)))
		n += len(x.Value)
	case *SetResponse_Error:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Error)))
		n += len(x.Error)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type RemoveRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *RemoveRequest) Reset()                    { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()               {}
func (*RemoveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RemoveRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RemoveResponse struct {
	// Types that are valid to be assigned to RemoveResponseOneOf:
	//	*RemoveResponse_Value
	//	*RemoveResponse_Error
	RemoveResponseOneOf isRemoveResponse_RemoveResponseOneOf `protobuf_oneof:"remove_response_one_of"`
}

func (m *RemoveResponse) Reset()                    { *m = RemoveResponse{} }
func (m *RemoveResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveResponse) ProtoMessage()               {}
func (*RemoveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type isRemoveResponse_RemoveResponseOneOf interface {
	isRemoveResponse_RemoveResponseOneOf()
}

type RemoveResponse_Value struct {
	Value string `protobuf:"bytes,1,opt,name=value,oneof"`
}
type RemoveResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,oneof"`
}

func (*RemoveResponse_Value) isRemoveResponse_RemoveResponseOneOf() {}
func (*RemoveResponse_Error) isRemoveResponse_RemoveResponseOneOf() {}

func (m *RemoveResponse) GetRemoveResponseOneOf() isRemoveResponse_RemoveResponseOneOf {
	if m != nil {
		return m.RemoveResponseOneOf
	}
	return nil
}

func (m *RemoveResponse) GetValue() string {
	if x, ok := m.GetRemoveResponseOneOf().(*RemoveResponse_Value); ok {
		return x.Value
	}
	return ""
}

func (m *RemoveResponse) GetError() string {
	if x, ok := m.GetRemoveResponseOneOf().(*RemoveResponse_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RemoveResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RemoveResponse_OneofMarshaler, _RemoveResponse_OneofUnmarshaler, _RemoveResponse_OneofSizer, []interface{}{
		(*RemoveResponse_Value)(nil),
		(*RemoveResponse_Error)(nil),
	}
}

func _RemoveResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RemoveResponse)
	// remove_response_one_of
	switch x := m.RemoveResponseOneOf.(type) {
	case *RemoveResponse_Value:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Value)
	case *RemoveResponse_Error:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Error)
	case nil:
	default:
		return fmt.Errorf("RemoveResponse.RemoveResponseOneOf has unexpected type %T", x)
	}
	return nil
}

func _RemoveResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RemoveResponse)
	switch tag {
	case 1: // remove_response_one_of.value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.RemoveResponseOneOf = &RemoveResponse_Value{x}
		return true, err
	case 2: // remove_response_one_of.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.RemoveResponseOneOf = &RemoveResponse_Error{x}
		return true, err
	default:
		return false, nil
	}
}

func _RemoveResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RemoveResponse)
	// remove_response_one_of
	switch x := m.RemoveResponseOneOf.(type) {
	case *RemoveResponse_Value:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Value)))
		n += len(x.Value)
	case *RemoveResponse_Error:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Error)))
		n += len(x.Error)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*KeyValuePair)(nil), "db.KeyValuePair")
	proto.RegisterType((*ListRequest)(nil), "db.ListRequest")
	proto.RegisterType((*GetRequest)(nil), "db.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "db.GetResponse")
	proto.RegisterType((*SetResponse)(nil), "db.SetResponse")
	proto.RegisterType((*RemoveRequest)(nil), "db.RemoveRequest")
	proto.RegisterType((*RemoveResponse)(nil), "db.RemoveResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for KeyValueStore service

type KeyValueStoreClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (KeyValueStore_ListClient, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Set(ctx context.Context, in *KeyValuePair, opts ...grpc.CallOption) (*SetResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
}

type keyValueStoreClient struct {
	cc *grpc.ClientConn
}

func NewKeyValueStoreClient(cc *grpc.ClientConn) KeyValueStoreClient {
	return &keyValueStoreClient{cc}
}

func (c *keyValueStoreClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (KeyValueStore_ListClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_KeyValueStore_serviceDesc.Streams[0], c.cc, "/db.KeyValueStore/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &keyValueStoreListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KeyValueStore_ListClient interface {
	Recv() (*KeyValuePair, error)
	grpc.ClientStream
}

type keyValueStoreListClient struct {
	grpc.ClientStream
}

func (x *keyValueStoreListClient) Recv() (*KeyValuePair, error) {
	m := new(KeyValuePair)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *keyValueStoreClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/db.KeyValueStore/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) Set(ctx context.Context, in *KeyValuePair, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := grpc.Invoke(ctx, "/db.KeyValueStore/Set", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueStoreClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	out := new(RemoveResponse)
	err := grpc.Invoke(ctx, "/db.KeyValueStore/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for KeyValueStore service

type KeyValueStoreServer interface {
	List(*ListRequest, KeyValueStore_ListServer) error
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Set(context.Context, *KeyValuePair) (*SetResponse, error)
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
}

func RegisterKeyValueStoreServer(s *grpc.Server, srv KeyValueStoreServer) {
	s.RegisterService(&_KeyValueStore_serviceDesc, srv)
}

func _KeyValueStore_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KeyValueStoreServer).List(m, &keyValueStoreListServer{stream})
}

type KeyValueStore_ListServer interface {
	Send(*KeyValuePair) error
	grpc.ServerStream
}

type keyValueStoreListServer struct {
	grpc.ServerStream
}

func (x *keyValueStoreListServer) Send(m *KeyValuePair) error {
	return x.ServerStream.SendMsg(m)
}

func _KeyValueStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.KeyValueStore/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValuePair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.KeyValueStore/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).Set(ctx, req.(*KeyValuePair))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueStore_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueStoreServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.KeyValueStore/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueStoreServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KeyValueStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "db.KeyValueStore",
	HandlerType: (*KeyValueStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _KeyValueStore_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _KeyValueStore_Set_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _KeyValueStore_Remove_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _KeyValueStore_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kvs/kvs.proto",
}

func init() { proto.RegisterFile("kvs/kvs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x93, 0x46, 0x0b, 0x4e, 0x4d, 0x5b, 0x47, 0x2d, 0x21, 0x07, 0xd1, 0x3d, 0x15, 0xc1,
	0xf8, 0x0f, 0x7c, 0x00, 0x2f, 0x15, 0xf4, 0x20, 0x89, 0x78, 0xf0, 0x12, 0x1a, 0x3a, 0x4a, 0x89,
	0x76, 0xeb, 0xee, 0x36, 0xd0, 0x27, 0xf4, 0xb5, 0x64, 0x77, 0xbb, 0x9a, 0x5a, 0xbd, 0xd8, 0x5b,
	0xe6, 0x9b, 0x6f, 0x7f, 0x1f, 0x33, 0x13, 0x08, 0xcb, 0x4a, 0x9e, 0x96, 0x95, 0x4c, 0xa6, 0x82,
	0x2b, 0x8e, 0x8d, 0x51, 0xc1, 0xae, 0x60, 0xfb, 0x96, 0xe6, 0x8f, 0xc3, 0xd7, 0x19, 0xdd, 0x0f,
	0xc7, 0x02, 0xbb, 0x10, 0x94, 0x34, 0x8f, 0xfc, 0x43, 0xbf, 0xbf, 0x95, 0xea, 0x4f, 0xdc, 0x83,
	0xcd, 0x4a, 0xb7, 0xa3, 0x86, 0xd1, 0x6c, 0xc1, 0x42, 0x68, 0xdd, 0x8d, 0xa5, 0x4a, 0xe9, 0x7d,
	0x46, 0x52, 0xb1, 0x03, 0x80, 0x01, 0xb9, 0x6a, 0x15, 0xc2, 0x1e, 0xa0, 0x65, 0xfa, 0x72, 0xca,
	0x27, 0x92, 0xb0, 0xe7, 0x98, 0xc6, 0x72, 0xe3, 0x2d, 0xa8, 0x5a, 0x27, 0x21, 0xb8, 0xb0, 0x59,
	0x5a, 0x37, 0xe5, 0xf5, 0x3e, 0xec, 0xbe, 0x90, 0xca, 0xc5, 0xe2, 0x7d, 0xce, 0x27, 0x94, 0xf3,
	0x67, 0x4d, 0xcd, 0xd6, 0xa3, 0xca, 0x5f, 0xa8, 0x47, 0x10, 0xa6, 0xf4, 0xc6, 0x2b, 0xfa, 0x7b,
	0x9c, 0x27, 0x68, 0x3b, 0xcb, 0x3f, 0xb3, 0x23, 0xe8, 0x09, 0x43, 0xf8, 0x19, 0x7f, 0xf1, 0xe1,
	0x43, 0xe8, 0x4e, 0x92, 0x29, 0x2e, 0x08, 0x4f, 0x60, 0x43, 0xef, 0x1a, 0x3b, 0xc9, 0xa8, 0x48,
	0x6a, 0x5b, 0x8f, 0xbb, 0x5a, 0xa8, 0x9f, 0x8f, 0x79, 0x67, 0x3e, 0xf6, 0x21, 0x18, 0x90, 0xc2,
	0xb6, 0x6e, 0x7e, 0x1f, 0x25, 0xee, 0x7c, 0xd5, 0x36, 0x8f, 0x79, 0x78, 0x0c, 0x41, 0x46, 0x0a,
	0x57, 0x30, 0xd6, 0x9b, 0x2d, 0x79, 0xcf, 0xa1, 0x69, 0x47, 0xc6, 0x1d, 0xdd, 0x5c, 0xda, 0x50,
	0x8c, 0x75, 0xc9, 0x3d, 0x29, 0x9a, 0xe6, 0x37, 0xbb, 0xfc, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x2d,
	0xc3, 0xee, 0xea, 0x77, 0x02, 0x00, 0x00,
}
